

services:
  frontend:
    build:
      context: .
      args:
        - VITE_API_URL=${VITE_API_URL}
    ports:
      - "80:80"
    environment:
      - API_URL=${API_URL}
    restart: unless-stopped